services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DB_FINANCE_API;User=sa;Password=Interview@2025;TrustServerCertificate=True;
    networks:
      - backend-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Interview@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend-network
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:

networks:
  backend-network: